var NavMenu={
    $nav:$("#nav"),
    open:function(){
        $body.addClass("nav-open");
        filmsList.speed=1;
        filmsList.lockCenter=false;
        filmsList.refresh();
        //films.enabled=false;
    },
    close:function(){
        $body.removeClass("nav-open");
        filmsList.speed=1.5;
        filmsList.lockCenter=true;
        filmsList.refresh();
        //films.enabled=true;
    },
    toggle:function(){
        if($body.is(".nav-open")){
            this.close();
        }else{
            this.open();
        }
    },
    __init:function () {
        $body.on("click","[data-nav-menu-toggle]",function(){
            NavMenu.toggle()
        })
    }
};
window.NavMenu=NavMenu;